### ISSUE TITLE
PHP's code is not correct

### ISSUE THREAD

**Issue by trendoman** [GroveOS/Sapling#3]
https://github.com/GroveOS/Sapling/blob/04ef10250c9580fc36f90376e5b9574279324ff1/embed/sapling/funcs/core.html#L7

Hey @GroveOS, let me suggest a replacement that I've written after seeing that line above. Peek at [**Cms Fu Sapling » embed**](https://github.com/trendoman/Cms-Fu/tree/master/Sapling/embed) function and feel free to *embed* it to the project. I really hope ☺ you find it usable!
– @trendoman

**Comment by matthewlarkin** [comment]
Thank you @trendoman! It has been _embedded_ 😄
